[profile.default]
src            = "src"
out            = "out"
libs           = ["lib"]
verbosity      = 3
solc           = "0.8.16"
optimizer      = true
optimizer_runs = 200

[fuzz]
runs = 5_000

[profile.ci.fuzz]
runs = 250_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
